# Spring Configuration
spring:
   application:
      name: mysite
   # Dev Tools -live reload 활성화
   devtools:
      livereload:
         enabled: true
   # mvc
   mvc:
      # URL Resource Mapping 하나만 등록 가능
      static-path-pattern: /assets/**
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   web:
      resources:
         # assets로 들어오면 /assets/로 가서 찾고 없으면 file:/mysite-uploads/가서 찾기
         static-location: classpath:/assets/, file:/mysite-uploads/
   # Multipart Resolver 설정
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
   # MessageSource: message resources(internationalization, i18n)
   messages:
      always-message-format: true
      basename: web/messages_ko
      encoding: utf-8
   aop:
      # AutoProxy
      auto: true
      proxy0target-class: true
# server
server:
   port: 9090